services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./backend
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/venv
    ports:
      - '5005:5005'
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - backend
      
volumes:
  data:
  logs:
